version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - travel_network 
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: travel_app
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - travel_network 

networks:
  travel_network:
    driver: bridge  # Default driver is 'bridge', which allows communication between containers

volumes:
  postgres_data:

